FROM node:16.18-alpine3.16
EXPOSE 3000
WORKDIR /app

COPY ./frontend/package.json ./frontend/yarn.lock ./
COPY ./shared ./shared

RUN sed -i -e 's/:..\/shared/:\/app\/shared/g' package.json

RUN yarn install
COPY ./frontend .

ENTRYPOINT ["yarn"]
CMD ["dev"]